[build]
  functions = "netlify/functions" # Specify the directory where your serverless functions are located
  
[build.environment]
  NODE_VERSION = "14" # Specify the Node.js version

[[redirects]]
  from = "/*" # Redirect all requests to the serverless function
  to = "/.netlify/functions/app"
  status = 200

[dev]
  functionsPort = 9000 # Specify the port for local function testing
